language: php

php:
  - 7.2

git:
  depth: 3

env:
  - version=L6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest;
  - if [[ $version = 'L56' ]]; then travis_retry composer require --dev --update-with-dependencies --no-suggest --no-interaction orchestra/testbench:"^4.0" laravel/framework:"^6.0"; fi
script: vendor/bin/phpunit

branches:
  only:
    - master
